project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: My Projects
      - href: cv.qmd
        text: Resume
      - href: contact.qmd
        text: Contact Me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




